"""add ai model routes table

Revision ID: 218100ec838d
Revises: 88978643dc4e
Create Date: 2026-09-14 19:23:22.105741
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218100ec838d'
down_revision: str | None = '88978643dc4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_routes',
    sa.Column('task_category', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('fallback_model_id', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_ai_model_routes_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_model_routes')),
    sa.UniqueConstraint('task_category', name=op.f('uq_ai_model_routes_task_category'))
    )
    op.create_index(op.f('ix_ai_model_routes_task_category'), 'ai_model_routes', ['task_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_model_routes_task_category'), table_name='ai_model_routes')
    op.drop_table('ai_model_routes')
    # ### end Alembic commands ###
