"""add platform insight tables

Revision ID: 2a86ad34e4e9
Revises: 4f1d9a2c2f43
Create Date: 2026-08-25 11:17:36.996089
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a86ad34e4e9"
down_revision: str | None = "4f1d9a2c2f43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_campaigns",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("objective", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("effective_status", sa.String(length=30), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("start_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("stop_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_platform_campaigns_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_campaigns")),
        sa.UniqueConstraint(
            "client_id",
            "integration_key",
            "external_id",
            name=op.f("uq_platform_campaigns_client_id"),
        ),
    )
    op.create_index(
        op.f("ix_platform_campaigns_client_id"), "platform_campaigns", ["client_id"], unique=False
    )
    op.create_index(
        "ix_platform_campaigns_client_key",
        "platform_campaigns",
        ["client_id", "integration_key"],
        unique=False,
    )
    op.create_table(
        "platform_delivery_issues",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column(
            "detail",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rec_key", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_platform_delivery_issues_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_delivery_issues")),
        sa.UniqueConstraint(
            "client_id",
            "integration_key",
            "rec_key",
            name=op.f("uq_platform_delivery_issues_client_id"),
        ),
    )
    op.create_index(
        op.f("ix_platform_delivery_issues_client_id"),
        "platform_delivery_issues",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_delivery_issues_client_status",
        "platform_delivery_issues",
        ["client_id", "status"],
        unique=False,
    )
    op.create_table(
        "platform_metrics_daily",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("impressions", sa.BigInteger(), nullable=False),
        sa.Column("clicks", sa.BigInteger(), nullable=False),
        sa.Column("spend", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reach", sa.BigInteger(), nullable=False),
        sa.Column("frequency", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("cpm", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("cpc", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("conversions", sa.BigInteger(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "actions",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "cost_per_action_type",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "breakdowns",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_platform_metrics_daily_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_metrics_daily")),
        sa.UniqueConstraint(
            "client_id",
            "integration_key",
            "entity_type",
            "entity_id",
            "date",
            name=op.f("uq_platform_metrics_daily_client_id"),
        ),
    )
    op.create_index(
        "ix_platform_metrics_daily_client_date",
        "platform_metrics_daily",
        ["client_id", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_metrics_daily_client_id"),
        "platform_metrics_daily",
        ["client_id"],
        unique=False,
    )
    op.create_table(
        "platform_recommendations",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=30), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=60), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("importance", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rec_key", sa.String(length=160), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_platform_recommendations_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_recommendations")),
        sa.UniqueConstraint(
            "client_id",
            "integration_key",
            "rec_key",
            name=op.f("uq_platform_recommendations_client_id"),
        ),
    )
    op.create_index(
        op.f("ix_platform_recommendations_client_id"),
        "platform_recommendations",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_recommendations_client_status",
        "platform_recommendations",
        ["client_id", "status"],
        unique=False,
    )
    op.create_table(
        "platform_ad_sets",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("effective_status", sa.String(length=30), nullable=True),
        sa.Column("daily_budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("lifetime_budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "targeting_summary",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "raw_payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["platform_campaigns.id"],
            name=op.f("fk_platform_ad_sets_campaign_id_platform_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_platform_ad_sets_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_ad_sets")),
        sa.UniqueConstraint(
            "client_id",
            "integration_key",
            "external_id",
            name=op.f("uq_platform_ad_sets_client_id"),
        ),
    )
    op.create_index(
        "ix_platform_ad_sets_campaign", "platform_ad_sets", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_ad_sets_client_id"), "platform_ad_sets", ["client_id"], unique=False
    )
    op.create_table(
        "platform_ads",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("ad_set_id", sa.Uuid(), nullable=False),
        sa.Column("integration_key", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("effective_status", sa.String(length=30), nullable=True),
        sa.Column(
            "creative_summary",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "issues_info",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "ad_review_feedback",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "raw_payload",
            sa.JSON(none_as_null=True).with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_set_id"],
            ["platform_ad_sets.id"],
            name=op.f("fk_platform_ads_ad_set_id_platform_ad_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_platform_ads_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_ads")),
        sa.UniqueConstraint(
            "client_id", "integration_key", "external_id", name=op.f("uq_platform_ads_client_id")
        ),
    )
    op.create_index("ix_platform_ads_ad_set", "platform_ads", ["ad_set_id"], unique=False)
    op.create_index(op.f("ix_platform_ads_client_id"), "platform_ads", ["client_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_platform_ads_client_id"), table_name="platform_ads")
    op.drop_index("ix_platform_ads_ad_set", table_name="platform_ads")
    op.drop_table("platform_ads")
    op.drop_index(op.f("ix_platform_ad_sets_client_id"), table_name="platform_ad_sets")
    op.drop_index("ix_platform_ad_sets_campaign", table_name="platform_ad_sets")
    op.drop_table("platform_ad_sets")
    op.drop_index(
        "ix_platform_recommendations_client_status", table_name="platform_recommendations"
    )
    op.drop_index(
        op.f("ix_platform_recommendations_client_id"), table_name="platform_recommendations"
    )
    op.drop_table("platform_recommendations")
    op.drop_index(op.f("ix_platform_metrics_daily_client_id"), table_name="platform_metrics_daily")
    op.drop_index("ix_platform_metrics_daily_client_date", table_name="platform_metrics_daily")
    op.drop_table("platform_metrics_daily")
    op.drop_index(
        "ix_platform_delivery_issues_client_status", table_name="platform_delivery_issues"
    )
    op.drop_index(
        op.f("ix_platform_delivery_issues_client_id"), table_name="platform_delivery_issues"
    )
    op.drop_table("platform_delivery_issues")
    op.drop_index("ix_platform_campaigns_client_key", table_name="platform_campaigns")
    op.drop_index(op.f("ix_platform_campaigns_client_id"), table_name="platform_campaigns")
    op.drop_table("platform_campaigns")
    # ### end Alembic commands ###
