"""add analytics_breakdowns table

Revision ID: 5c79164e1108
Revises: d4f7a29c8b1e
Create Date: 2026-08-31 18:13:05.021517
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c79164e1108'
down_revision: str | None = 'd4f7a29c8b1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_breakdowns',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('integration_key', sa.String(length=30), nullable=False),
    sa.Column('breakdown_type', sa.String(length=30), nullable=False),
    sa.Column('dimension', sa.String(length=500), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_analytics_breakdowns_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_breakdowns')),
    sa.UniqueConstraint('client_id', 'integration_key', 'breakdown_type', 'dimension', name=op.f('uq_analytics_breakdowns_client_id'))
    )
    op.create_index(op.f('ix_analytics_breakdowns_client_id'), 'analytics_breakdowns', ['client_id'], unique=False)
    op.create_index('ix_analytics_breakdowns_client_key_type', 'analytics_breakdowns', ['client_id', 'integration_key', 'breakdown_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_breakdowns_client_key_type', table_name='analytics_breakdowns')
    op.drop_index(op.f('ix_analytics_breakdowns_client_id'), table_name='analytics_breakdowns')
    op.drop_table('analytics_breakdowns')
    # ### end Alembic commands ###
