"""add integrations.login_customer_id

Revision ID: 62e0e3b9228a
Revises: b08a6f1b6703
Create Date: 2026-08-25 17:14:10.927778
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62e0e3b9228a"
down_revision: str | None = "b08a6f1b6703"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "integrations", sa.Column("login_customer_id", sa.String(length=40), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integrations", "login_customer_id")
    # ### end Alembic commands ###
