"""add auto plan generation log table

Revision ID: 964831eebfcd
Revises: 218100ec838d
Create Date: 2026-09-15 11:35:06.947307
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964831eebfcd'
down_revision: str | None = '218100ec838d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_plan_generation_log',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_auto_plan_generation_log_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auto_plan_generation_log')),
    sa.UniqueConstraint('client_id', 'period', name=op.f('uq_auto_plan_generation_log_client_id'))
    )
    op.create_index(op.f('ix_auto_plan_generation_log_client_id'), 'auto_plan_generation_log', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_plan_generation_log_client_id'), table_name='auto_plan_generation_log')
    op.drop_table('auto_plan_generation_log')
    # ### end Alembic commands ###
