"""single-domain rbac schema

Revision ID: adc6dd263daf
Revises: 
Create Date: 2026-07-09 15:00:53.834747
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adc6dd263daf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'user', name='user_role'), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('clients',
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('business_type', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=60), nullable=True),
    sa.Column('markets', sa.Text(), nullable=True),
    sa.Column('about_brand', sa.Text(), nullable=True),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('brand_extracted', sa.Text(), nullable=True),
    sa.Column('color_guidelines', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'onboarding', 'archived', name='client_status'), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('onboarding', 'discovery', 'active', 'optimize', 'retention', name='client_pipeline_stage'), nullable=False),
    sa.Column('spend_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('leads_total', sa.Integer(), nullable=False),
    sa.Column('cpl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_clients_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('slug', name=op.f('uq_clients_slug'))
    )
    op.create_index(op.f('ix_clients_pipeline_stage'), 'clients', ['pipeline_stage'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('ai_chats',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context_type', sa.String(length=40), nullable=True),
    sa.Column('context_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_ai_chats_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_chats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_chats'))
    )
    op.create_index(op.f('ix_ai_chats_client_id'), 'ai_chats', ['client_id'], unique=False)
    op.create_index('ix_ai_chats_client_user', 'ai_chats', ['client_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_ai_chats_context_type'), 'ai_chats', ['context_type'], unique=False)
    op.create_index(op.f('ix_ai_chats_user_id'), 'ai_chats', ['user_id'], unique=False)
    op.create_table('ai_sources',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('document', 'url', 'ga4', 'search_console', 'google_ads', 'meta', 'analytics_snapshot', name='ai_source_type'), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_ai_sources_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_sources'))
    )
    op.create_index(op.f('ix_ai_sources_client_id'), 'ai_sources', ['client_id'], unique=False)
    op.create_table('analytics_daily',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'facebook', 'youtube', 'tiktok', 'x', 'linkedin', 'pinterest', 'google', 'email', 'other', name='social_platform'), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('leads', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_analytics_daily_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_daily')),
    sa.UniqueConstraint('client_id', 'date', 'platform', name=op.f('uq_analytics_daily_client_id'))
    )
    op.create_index('ix_analytics_daily_client_date', 'analytics_daily', ['client_id', 'date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_client_id'), 'analytics_daily', ['client_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_label', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_audit_log_client_id_clients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_client_id'), 'audit_log', ['client_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('client_assignments',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_client_assignments_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_assignments_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_client_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_assignments')),
    sa.UniqueConstraint('client_id', 'user_id', name=op.f('uq_client_assignments_client_id'))
    )
    op.create_index(op.f('ix_client_assignments_client_id'), 'client_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_assignments_user_id'), 'client_assignments', ['user_id'], unique=False)
    op.create_table('client_brand_colors',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('hex', sa.String(length=9), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_brand_colors_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_brand_colors'))
    )
    op.create_index(op.f('ix_client_brand_colors_client_id'), 'client_brand_colors', ['client_id'], unique=False)
    op.create_table('client_brand_fonts',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('family', sa.String(length=120), nullable=False),
    sa.Column('usage', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_brand_fonts_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_brand_fonts'))
    )
    op.create_index(op.f('ix_client_brand_fonts_client_id'), 'client_brand_fonts', ['client_id'], unique=False)
    op.create_table('client_contacts',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('client', 'inwork', name='contact_side'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_contacts_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_contacts'))
    )
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_index('ix_client_contacts_client_side', 'client_contacts', ['client_id', 'side'], unique=False)
    op.create_table('client_platforms',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_platforms_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_platforms')),
    sa.UniqueConstraint('client_id', 'channel', name=op.f('uq_client_platforms_client_id'))
    )
    op.create_index(op.f('ix_client_platforms_client_id'), 'client_platforms', ['client_id'], unique=False)
    op.create_table('compliance_entries',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('brand_voice', 'banned', 'required', 'rule', 'note', name='compliance_kind'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_compliance_entries_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_compliance_entries_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_entries'))
    )
    op.create_index(op.f('ix_compliance_entries_client_id'), 'compliance_entries', ['client_id'], unique=False)
    op.create_index('ix_compliance_entries_client_kind', 'compliance_entries', ['client_id', 'kind'], unique=False)
    op.create_table('conversations',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('email', 'sms', 'whatsapp', 'instagram', 'facebook', 'webform', 'internal', name='conversation_source'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_conversations_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_client_id'), 'conversations', ['client_id'], unique=False)
    op.create_index('ix_conversations_client_last_msg', 'conversations', ['client_id', 'last_message_at'], unique=False)
    op.create_table('documents',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('brand', 'compliance', 'goals', 'contract', 'brief', 'creative', 'other', name='document_kind'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_documents_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index('ix_documents_client_kind', 'documents', ['client_id', 'kind'], unique=False)
    op.create_table('integrations',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Enum('ga4', 'search_console', 'google_ads', 'google_lsa', 'meta', 'linkedin', name='integration_key'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', 'pending', name='integration_status'), nullable=False),
    sa.Column('account_label', sa.String(length=200), nullable=True),
    sa.Column('external_account_id', sa.String(length=160), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_integrations_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('client_id', 'key', name=op.f('uq_integrations_client_id'))
    )
    op.create_index(op.f('ix_integrations_client_id'), 'integrations', ['client_id'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    op.create_table('marketing_events',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('campaign', 'email', 'ad', 'review', 'content', 'meeting', name='event_type'), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'facebook', 'youtube', 'tiktok', 'x', 'linkedin', 'pinterest', 'google', 'email', 'other', name='social_platform'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('draft', 'scheduled', 'published', 'archived', name='event_stage'), nullable=False),
    sa.Column('approval_status', sa.Enum('approved', 'pending', 'changes_requested', 'rejected', name='approval_status'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_marketing_events_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_marketing_events_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_marketing_events_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_events'))
    )
    op.create_index(op.f('ix_marketing_events_approval_status'), 'marketing_events', ['approval_status'], unique=False)
    op.create_index('ix_marketing_events_client_date', 'marketing_events', ['client_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_marketing_events_client_id'), 'marketing_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_marketing_events_platform'), 'marketing_events', ['platform'], unique=False)
    op.create_index(op.f('ix_marketing_events_stage'), 'marketing_events', ['stage'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('strategy', 'creative', 'ads', 'content', 'analytics', 'compliance', 'admin', name='task_category'), nullable=False),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', name='task_status'), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_plan_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_plan_tasks_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_plan_tasks_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_tasks'))
    )
    op.create_index(op.f('ix_plan_tasks_assignee_id'), 'plan_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_client_id'), 'plan_tasks', ['client_id'], unique=False)
    op.create_index('ix_plan_tasks_client_status', 'plan_tasks', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_plan_tasks_due_date'), 'plan_tasks', ['due_date'], unique=False)
    op.create_table('recommendation_actions',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('rec_key', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.Enum('accepted', 'modified', 'rejected', name='recommendation_decision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_recommendation_actions_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_recommendation_actions_decided_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_actions'))
    )
    op.create_index(op.f('ix_recommendation_actions_client_id'), 'recommendation_actions', ['client_id'], unique=False)
    op.create_index('ix_recommendation_actions_client_rec', 'recommendation_actions', ['client_id', 'rec_key'], unique=False)
    op.create_table('reports',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('performance', 'compliance', 'strategy', 'executive', 'custom', name='report_kind'), nullable=False),
    sa.Column('format', sa.Enum('pdf', 'excel', 'visual', name='report_format'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=True),
    sa.Column('channels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('save_to_outlook_draft', sa.Boolean(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_reports_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_client_created', 'reports', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    op.create_table('strategy_visuals',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_strategy_visuals_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_strategy_visuals_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_visuals'))
    )
    op.create_index(op.f('ix_strategy_visuals_client_id'), 'strategy_visuals', ['client_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='ai_chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['ai_chats.id'], name=op.f('fk_ai_chat_messages_chat_id_ai_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_chat_messages'))
    )
    op.create_index(op.f('ix_ai_chat_messages_chat_id'), 'ai_chat_messages', ['chat_id'], unique=False)
    op.create_table('ai_chat_sources',
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['ai_chats.id'], name=op.f('fk_ai_chat_sources_chat_id_ai_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['ai_sources.id'], name=op.f('fk_ai_chat_sources_source_id_ai_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'source_id', name=op.f('pk_ai_chat_sources'))
    )
    op.create_table('compliance_docs',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_compliance_docs_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_compliance_docs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_docs'))
    )
    op.create_index(op.f('ix_compliance_docs_client_id'), 'compliance_docs', ['client_id'], unique=False)
    op.create_table('event_activity',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['marketing_events.id'], name=op.f('fk_event_activity_event_id_marketing_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_activity_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_activity'))
    )
    op.create_index(op.f('ix_event_activity_event_id'), 'event_activity', ['event_id'], unique=False)
    op.create_table('event_ads',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('objective', sa.Enum('awareness', 'traffic', 'engagement', 'leads', 'conversions', name='ad_objective'), nullable=False),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('bid_strategy', sa.String(length=60), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['marketing_events.id'], name=op.f('fk_event_ads_event_id_marketing_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_ads')),
    sa.UniqueConstraint('event_id', name=op.f('uq_event_ads_event_id'))
    )
    op.create_table('event_assets',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_event_assets_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['marketing_events.id'], name=op.f('fk_event_assets_event_id_marketing_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_assets'))
    )
    op.create_index(op.f('ix_event_assets_event_id'), 'event_assets', ['event_id'], unique=False)
    op.create_table('event_posts',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['marketing_events.id'], name=op.f('fk_event_posts_event_id_marketing_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_posts')),
    sa.UniqueConstraint('event_id', name=op.f('uq_event_posts_event_id'))
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('folder', sa.Enum('inbox', 'sent', 'drafts', 'archive', 'spam', 'trash', name='message_folder'), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_messages_sender_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_category'), 'messages', ['category'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_folder'), 'messages', ['folder'], unique=False)
    op.create_table('message_attachments',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_message_attachments_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_attachments'))
    )
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.create_table('message_recipients',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('to', 'cc', 'bcc', name='recipient_kind'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_recipients_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_recipients'))
    )
    op.create_index(op.f('ix_message_recipients_message_id'), 'message_recipients', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_recipients_message_id'), table_name='message_recipients')
    op.drop_table('message_recipients')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index(op.f('ix_messages_folder'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_category'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('event_posts')
    op.drop_index(op.f('ix_event_assets_event_id'), table_name='event_assets')
    op.drop_table('event_assets')
    op.drop_table('event_ads')
    op.drop_index(op.f('ix_event_activity_event_id'), table_name='event_activity')
    op.drop_table('event_activity')
    op.drop_index(op.f('ix_compliance_docs_client_id'), table_name='compliance_docs')
    op.drop_table('compliance_docs')
    op.drop_table('ai_chat_sources')
    op.drop_index(op.f('ix_ai_chat_messages_chat_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_strategy_visuals_client_id'), table_name='strategy_visuals')
    op.drop_table('strategy_visuals')
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_index('ix_reports_client_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_recommendation_actions_client_rec', table_name='recommendation_actions')
    op.drop_index(op.f('ix_recommendation_actions_client_id'), table_name='recommendation_actions')
    op.drop_table('recommendation_actions')
    op.drop_index(op.f('ix_plan_tasks_due_date'), table_name='plan_tasks')
    op.drop_index('ix_plan_tasks_client_status', table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_client_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_assignee_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_marketing_events_stage'), table_name='marketing_events')
    op.drop_index(op.f('ix_marketing_events_platform'), table_name='marketing_events')
    op.drop_index(op.f('ix_marketing_events_client_id'), table_name='marketing_events')
    op.drop_index('ix_marketing_events_client_date', table_name='marketing_events')
    op.drop_index(op.f('ix_marketing_events_approval_status'), table_name='marketing_events')
    op.drop_table('marketing_events')
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_client_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('ix_documents_client_kind', table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_client_last_msg', table_name='conversations')
    op.drop_index(op.f('ix_conversations_client_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_compliance_entries_client_kind', table_name='compliance_entries')
    op.drop_index(op.f('ix_compliance_entries_client_id'), table_name='compliance_entries')
    op.drop_table('compliance_entries')
    op.drop_index(op.f('ix_client_platforms_client_id'), table_name='client_platforms')
    op.drop_table('client_platforms')
    op.drop_index('ix_client_contacts_client_side', table_name='client_contacts')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_client_brand_fonts_client_id'), table_name='client_brand_fonts')
    op.drop_table('client_brand_fonts')
    op.drop_index(op.f('ix_client_brand_colors_client_id'), table_name='client_brand_colors')
    op.drop_table('client_brand_colors')
    op.drop_index(op.f('ix_client_assignments_user_id'), table_name='client_assignments')
    op.drop_index(op.f('ix_client_assignments_client_id'), table_name='client_assignments')
    op.drop_table('client_assignments')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_client_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_analytics_daily_client_id'), table_name='analytics_daily')
    op.drop_index('ix_analytics_daily_client_date', table_name='analytics_daily')
    op.drop_table('analytics_daily')
    op.drop_index(op.f('ix_ai_sources_client_id'), table_name='ai_sources')
    op.drop_table('ai_sources')
    op.drop_index(op.f('ix_ai_chats_user_id'), table_name='ai_chats')
    op.drop_index(op.f('ix_ai_chats_context_type'), table_name='ai_chats')
    op.drop_index('ix_ai_chats_client_user', table_name='ai_chats')
    op.drop_index(op.f('ix_ai_chats_client_id'), table_name='ai_chats')
    op.drop_table('ai_chats')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_pipeline_stage'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
