"""add client budgets table

Revision ID: e7f0c061955f
Revises: 12578158a8e7
Create Date: 2026-09-14 09:33:05.729540
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f0c061955f'
down_revision: str | None = '12578158a8e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_budgets',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('set_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_budgets_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], name=op.f('fk_client_budgets_set_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_budgets')),
    sa.UniqueConstraint('client_id', 'period', 'platform', name=op.f('uq_client_budgets_client_id'))
    )
    op.create_index(op.f('ix_client_budgets_client_id'), 'client_budgets', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_budgets_period'), 'client_budgets', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_budgets_period'), table_name='client_budgets')
    op.drop_index(op.f('ix_client_budgets_client_id'), table_name='client_budgets')
    op.drop_table('client_budgets')
    # ### end Alembic commands ###
