"""add plan task requirements, archived flag, assets, and notes

Revision ID: f824b63a3767
Revises: 964831eebfcd
Create Date: 2026-09-15 12:01:31.989116
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f824b63a3767'
down_revision: str | None = '964831eebfcd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_task_assets',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], name=op.f('fk_plan_task_assets_task_id_plan_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_task_assets'))
    )
    op.create_index(op.f('ix_plan_task_assets_task_id'), 'plan_task_assets', ['task_id'], unique=False)
    op.create_table('plan_task_notes',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], name=op.f('fk_plan_task_notes_task_id_plan_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plan_task_notes_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_task_notes'))
    )
    op.create_index(op.f('ix_plan_task_notes_task_id'), 'plan_task_notes', ['task_id'], unique=False)
    op.add_column('plan_tasks', sa.Column('requirements', sa.Text(), nullable=True))
    # NOT NULL with existing rows needs a server-side backfill default first
    # (see e.g. 1dd120a4fea0's task_priority precedent) — added, then cleared
    # so future inserts rely on the ORM/application default, not the DB.
    op.add_column(
        'plan_tasks',
        sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('plan_tasks', 'archived', server_default=None)
    op.create_index(op.f('ix_plan_tasks_archived'), 'plan_tasks', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_tasks_archived'), table_name='plan_tasks')
    op.drop_column('plan_tasks', 'archived')
    op.drop_column('plan_tasks', 'requirements')
    op.drop_index(op.f('ix_plan_task_notes_task_id'), table_name='plan_task_notes')
    op.drop_table('plan_task_notes')
    op.drop_index(op.f('ix_plan_task_assets_task_id'), table_name='plan_task_assets')
    op.drop_table('plan_task_assets')
    # ### end Alembic commands ###
