"""Async client for the OpenAI-compatible Chat Completions API.

This is the *second* LLM provider: the cross-provider QA layer uses it to review
content generated by Anthropic, so a different vendor independently checks the
output and single-vendor bias is countered.

Mirrors ``AnthropicClient``'s shape on purpose — same ``complete`` signature,
same ``is_configured`` gate, the same "instrument every call through one place"
usage recording, and the same graceful stance: it never runs when unconfigured.
Implemented over ``httpx`` (already a dependency, same as the Brave/ScrapingBee
integrations) rather than the vendor SDK, so any OpenAI-compatible endpoint works
via ``OPENAI_BASE_URL`` and no extra dependency is required.

Reads the key/model/base URL from settings — never hardcoded.
"""

from __future__ import annotations

import time

import httpx

from app.ai.pricing import UsageBreakdown
from app.ai.usage import AiUsageContext, record_usage
from app.core.config import get_settings
from app.core.exceptions import ServiceUnavailableError

_PROVIDER = "openai"


class OpenAIClient:
    def __init__(self, context: AiUsageContext | None = None, settings=None) -> None:
        self._settings = settings or get_settings().openai
        self._context = context  # optional instance-wide attribution default

    @property
    def is_configured(self) -> bool:
        return self._settings.is_configured

    async def complete(
        self,
        *,
        system: str,
        prompt: str,
        max_tokens: int | None = None,
        context: AiUsageContext | None = None,
    ) -> str:
        """One chat completion. Records token usage + cost, like the Anthropic client."""
        if not self.is_configured:
            raise ServiceUnavailableError("QA provider (OpenAI) is not configured.")

        model = self._settings.model
        ctx = context or self._context
        payload = {
            "model": model,
            "max_tokens": max_tokens or self._settings.max_tokens,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
        }
        headers = {
            "Authorization": f"Bearer {self._settings.api_key}",
            "Content-Type": "application/json",
        }
        url = self._settings.base_url.rstrip("/") + "/chat/completions"
        started = time.perf_counter()
        try:
            async with httpx.AsyncClient(timeout=self._settings.timeout_seconds) as http:
                resp = await http.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                body = resp.json()
        except Exception as exc:
            record_usage(
                context=ctx, provider=_PROVIDER, model=model, operation="complete",
                usage=None, status="error", error=str(exc)[:500],
                duration_ms=int((time.perf_counter() - started) * 1000),
            )
            raise
        record_usage(
            context=ctx, provider=_PROVIDER, model=model, operation="complete",
            usage=_usage_from_body(body), status="success",
            request_id=str(body.get("id") or "") or None,
            duration_ms=int((time.perf_counter() - started) * 1000),
        )
        return _text_of(body)


def _text_of(body: dict) -> str:
    choices = body.get("choices") or []
    if not choices:
        return ""
    message = (choices[0] or {}).get("message") or {}
    return str(message.get("content") or "")


def _usage_from_body(body: dict) -> UsageBreakdown:
    u = body.get("usage") or {}
    return UsageBreakdown(
        input_tokens=int(u.get("prompt_tokens", 0) or 0),
        output_tokens=int(u.get("completion_tokens", 0) or 0),
    )
